deployment = ${?DEPLOYMENT}

play.http.secret.key = """iWyJJryqCqMIau59yaTmZCeCO6BkSewEylsBq3CR0Hc="""
play.filters.hosts {
  allowed = ["127.0.0.1:"${?PLAY_HTTP_PORT}, "localhost:"${?PLAY_HTTP_PORT}, ${?PRIVATE_IP_ADDRESS}":"${?PLAY_HTTP_PORT}]
}

local{
  TOPOSOID_GRAPHDB_WEB_HOST = ${?TOPOSOID_GRAPHDB_WEB_HOST}
  TOPOSOID_GRAPHDB_WEB_PORT = ${?TOPOSOID_GRAPHDB_WEB_PORT}
  TOPOSOID_TABLE_VECTORDB_ACCESSOR_HOST = ${?TOPOSOID_TABLE_VECTORDB_ACCESSOR_HOST}
  TOPOSOID_TABLE_VECTORDB_ACCESSOR_PORT = ${?TOPOSOID_TABLE_VECTORDB_ACCESSOR_PORT}
  TOPOSOID_TABLE_VECTORDB_SEARCH_NUM_MAX = ${?TOPOSOID_TABLE_VECTORDB_SEARCH_NUM_MAX}
  TOPOSOID_COMMON_TABLE_RECOGNITION_HOST = ${?TOPOSOID_COMMON_TABLE_RECOGNITION_HOST}
  TOPOSOID_COMMON_TABLE_RECOGNITION_PORT = ${?TOPOSOID_COMMON_TABLE_RECOGNITION_PORT}
  TOPOSOID_DEDUCTION_UNIT_NAME = "EmbeddingWholeSentenceTableMatch"
  retryCallMicroserviceNum = 10
}

# メモリ上にバッファする最大サイズ
play.http.parser.maxMemoryBuffer = 1M

# ディスクにバッファする最大サイズ / ファイルアップロードなど
play.http.parser.maxDiskBuffer = 10M
